### ISSUE TITLE
Format exception with 1.9 SDK + async

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/stack_trace#1]
```
FormatException: Couldn't parse VM stack trace line '#5      main.<anonymous closure>.<<anonymous closure>_async_body> (file:///Users/kevmoo/source/github/source_gen.dart/test/project_generator_test.dart)'.
```

Dart VM version: 1.9.0-dev.7.1

CC @nex3

**Comment by kevmoo** [comment]
Related to fix for https://code.google.com/p/dart/issues/detail?id=22009

**Comment by kevmoo** [comment]
Repro:

* https://github.com/kevmoo/source_gen.dart
* branch: crash_i22009
* pub install
* dart test/project_generator_test.dart

**Comment by nex3** [comment]
For future bugs, it would be nice if you could distill repro cases down to a single script.
