### ISSUE TITLE
How expensive is a `Trace.current()`

### ISSUE THREAD

**Issue by escamoteur** [dart-lang/stack_trace#138]
Hi, 

I wonder if it costs a lot of performance to call `Trace.current()` on a regular basis or should this be avoided and only done when absolutely needed?

Cheers
Thomas

**Comment by osa1** [comment]
`Trace.current` calls [`StackTrace.current`](https://api.dart.dev/stable/3.5.3/dart-core/StackTrace/current.html`) and then lazily parses the frames as you access the fields.

Parsing overhead should be small compared to getting the stack traces, on all platforms.

So the question is "how fast is `StackTrace.current`".

According to https://github.com/dart-lang/sdk/issues/9579, on VM it's not "very slow" anymore. However it's not clear what that means, and the actual numbers of how long it takes to get a stack frame will depend on the call site and device/platform etc.

On the browser, both dart2js and dart2wasm create an `Error` object and then get the [`stack` property](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/stack), then convert it to a string.

You really have to benchmark and see if the performance is acceptable for your application. Even if I give you a concrete number ("takes X microseconds") the number will be different in your use case.

Closing as this is not an issue.
