### ISSUE TITLE
Chain.capture does not allow passing zoneValues 

### ISSUE THREAD

**Issue by johnmccutchan** [dart-lang/stack_trace#16]
[runZoned](https://api.dartlang.org/stable/1.20.1/dart-async/runZoned.html) provides a named parameter `Map zoneValues`. This is used by `flutter_tools` [here](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/base/context.dart#L65).

I would like to use Chain.capture here but I need to be able to pass `zoneValues` in.

**Comment by nex3** [comment]
Zones are automatically composed. You can just create another zone that has `zoneValues` and run that within the `Chain.capture()` call (or vice versa) and both zones will be active at once.
