### ISSUE TITLE
Chain.capture doesn't seem to get an async stack trace w/ DDC

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/stack_trace#26]
I'll try to work on a minimal reproduction today or tomorrow. Just posting for posterity.

**Comment by nex3** [comment]
Any update?

**Comment by matanlurey** [comment]
I have a reproduction case internally I think @vsmenon is aware of - we don't have a great way (yet) to compile applications with DDC externally, but I can post the code for posterity:

```dart
import 'dart:async';

import 'package:stack_trace/stack_trace.dart';
import 'package:test/test.dart';

void main() {
  test('should capture a "long" stack trace', () async {
    var traces = <StackTrace>[];
    Chain.capture(() {
      void foo() {
        throw new StateError('Foo should never be called');
      }

      void bar() {
        scheduleMicrotask(foo);
      }

      Timer.run(bar);
    }, onError: (e, s) {
      traces.add(s);
    });
    await new Future.delayed(const Duration(milliseconds: 10));
    print(traces);
  });
}
```

**Comment by vsmenon** [comment]
I think `package:stack_trace` is assuming identity on StackTrace objects (it looked like the chain was stored as an expando).  

DDC should now preserve identity & I'm seeing an async trace when I try this example on bleeding edge.  Will roll that fix internally sometime this week.

**Comment by matanlurey** [comment]
Thanks! I'm happy to close this then.
