### ISSUE TITLE
get the original stack trace

### ISSUE THREAD

**Issue by Keksinautin** [dart-lang/stack_trace#28]
Hi to all. 
As I understand now it is impossible to get the original stack trace from a `Trace` or a `Chain` object.
But it can be very helpful to show stack traces in the dev-tool browser console in a way that the current browser understands and can transform them using sorce-maps files. I am going to use the "pretty-print" format to show stack-traces in the "dev-mode" and an original browser format in the production mode of my application.
I am going to add an `originalTrace` property to the `Trace` and to the `Chain` classes and save there a `String` that was used to create these objects.
Dear authors, what do you think about this improvement? Any requirements, advices or suggestions?

**Comment by nex3** [comment]
Can you help me understand why you're using the `stack_trace` package if you don't want its stack trace format?

**Comment by Keksinautin** [comment]
Two main reasons: 
- I use it to parse stack traces into the "sentry format". But for this case the improvement is not necessary. The original stack trace is avalable to me.
- I use `Chain.capture` and there is no way as I understand to get the original stack trace inside the callback. Am I right?
