### ISSUE TITLE
Package stack_trace prevents breakpoints from working

### ISSUE THREAD

**Issue by Pacane** [dart-lang/stack_trace#3]
So I tried using the stack_trace package in my app, it works fine, except for this:

![screenshot](http://i.imgur.com/jy3HOlY.png)

If I remove the comments, the breakpoints don't work anymore. I'm using intelliJ ultimate with the Dart Plugin, with stack_trace version 1.3.2

Is this a known side-effect of using stack_trace or intended?

**Comment by zoechi** [comment]
Could be related to http://dartbug.com/23311
I don't know if I had this issue because the test package uses stack_trace or because it's just a coincidence that the problem occurred while you used stack_trace while it is in fact caused by something else..

**Comment by nex3** [comment]
This looks like a bug with the VM service that provides debugging support. It should be resilient to debugging within custom zones of any sort.

**Comment by Pacane** [comment]
So do I have to open a bug somewhere else?

**Comment by nex3** [comment]
Just follow the bug @zoechi linked above.
