### ISSUE TITLE
examples can show up on the pub site

### ISSUE THREAD

**Issue by bcko** [dart-lang/stack_trace#41]
The pub site can show example code for a package.
https://www.dartlang.org/tools/pub/package-layout#examples

Let me know if you want me to try working on this.

related issue : dart-lang/site-www#413

**Comment by devoncarew** [comment]
Closing - we have an example here as of https://github.com/dart-lang/stack_trace/commit/2194227245513190cc29eebb9f2e4d885cdb0899.
