### ISSUE TITLE
Add sample for Chain.terse

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/stack_trace#6]
Thanks for your package - it is really helpful!!!! but it took me quite a while to figure out how to handle Chain.terse / Trace.terse...

Could you add a little sample to your README?
```dart
    void run() {
        Chain.capture( () {
            _loadAsyncProxy();

        },onError: (final error,final Chain chain) {
            
            _logger.shout(error,chain.terse);
        });
    }
```

**Comment by nex3** [comment]
What exactly is confusing about it? It's just a getter, like any other getter in the language.

**Comment by MikeMitterer** [comment]
It's not confusing and it's not the getter - it's the "onError". I'm missing this part in your README. You are mentioning XXX.terse and you assume that everyone knows how to use it. Sure - it's not so hard to figure out but two ore three more lines in the README could save someone at least half an hour of searching for this in the API documentation.

**Comment by nex3** [comment]
`onError` isn't even mentioned in the README.

In general, the function of the README is to give a brief introduction to the package, not to document every part of it. That's what the API documentation is for.

**Comment by denis-aes** [comment]
This worse adding. Cause after reading big article http://news.dartlang.org/2016/01/unboxing-packages-stacktrace.html - I have to google for just 3 (!) lines of code that completes the article.

**Comment by rasuru** [comment]
I thought it's used like Chain.terse(() => // code) instead of what is written in the issue. But it didn't work so I went here to issues to see if anyone had problems with it. Would be nice to see in README, but that's just my opinion.
